# Generated by Django 5.0.2 on 2024-02-22 20:23

import identity.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_secret', models.CharField(default=identity.models.default_client_secret, editable=False, max_length=64, unique=True)),
                ('authorized_accounts', models.ManyToManyField(related_name='authorized_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
