# Generated by Django 5.0.2 on 2024-02-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='client_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
