# Generated by Django 5.0.2 on 2024-02-26 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_authorizationcode_account_authorizationcode_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationcode',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorization_codes', to='identity.client'),
        ),
    ]
