# Generated by Django 5.0.2 on 2024-02-26 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_authorizationcode_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorizationcode',
            old_name='value',
            new_name='code',
        ),
    ]
