version: '3.8'
services:
  sso-frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    networks:
      - lakelon_dev

  sso-backend:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
    networks:
      - lakelon_dev

networks:
  lakelon_dev:
    external: true
